version: '3'

services:
  server:
    build: .
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - redis
    restart: unless-stopped
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    hostname: redis
    networks:
      - redis
    volumes:
      - redis:/data
    restart: unless-stopped

networks:
  redis:

volumes:
  redis:
