version: '3'

services:
  ditto_bot:
    build: .
    image: binary_bot
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - redis
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    hostname: redis
    restart: unless-stopped
    networks:
      - redis
    volumes:
      - redis:/data

networks:
  redis:

volumes:
  redis:
